mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('book_check.urls')),
    path('', include('users.urls')),] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, LogoutView, LoginView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView, name='login'),
    path('logout/', LogoutView, name='logout'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset-confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

book_check/models.py
from django.contrib.auth.models import AbstractUser, User
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255)
    biography = models.TextField(blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name='Book name', db_index=True,)
    author = models.ForeignKey(Author, related_name='books', verbose_name='Author', on_delete=models.CASCADE)
    published_date = models.CharField(max_length=30, verbose_name='Originally published',)
    GENRES_TYPES = (
        (1, 'Classics'),
        (2, 'Action and Adventure'),
        (3, 'Fantasy'),
        (4, 'Horror'),
        (5, 'Novel'),
        (6, 'Historical Fiction'),
        (7, 'Dystopian'),
        (8, 'Detective and Mystery')
    )
    genres = models.IntegerField(verbose_name='Genres', choices=GENRES_TYPES,)
    description = models.TextField(verbose_name='Book description')
    cover_image = models.ImageField(upload_to='book_covers/', null=True, blank=True)

    def __str__(self):
        return f'"{self.title}" -  {self.author.name}'


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                )
    read_books = models.ManyToManyField('Book', blank=True)

    def is_read(self, book: Book):
        return book in self.read_books.all()

    def add_book(self, book: Book):
        if not self.is_read(book):
            self.read_books.add(book)
            self.save()

    def __str__(self):
        return self.user.username


class UserBookInteraction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    tags = models.CharField(max_length=50, blank=True)
    note = models.TextField(blank=True, null=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)],
                                              null=True, blank=True)

    class Meta:
        unique_together = ('profile', 'book')

    def get_user_rating(self, book: Book, profile: Profile):
        return self.rating

    def set_rating(self, new_rating):
        self.rating = new_rating
        self.save()

    @classmethod
    def get_or_none(cls, profile: Profile, book: Book):
        try:
            return cls.objects.get(profile=profile, book=book)
        except cls.DoesNotExist:
            return None

    @classmethod
    def get_rating_or_none(cls, profile: Profile, book: Book):
        try:
            return cls.objects.get(profile=profile, book=book).rating
        except cls.DoesNotExist:
            return None

    def __str__(self):
        return f"{self.profile.user.username} - {self.book.title}"

book_check/views/home.py
import random

from django.shortcuts import render

from ..models import Book


def home(request):
    """
        Shows the home page with books.
        If the user is registered, he sees a recommendation list for future reading.
    """
    books = Book.objects.order_by('?')[:6]
    if not request.user.is_authenticated:
        context = {
            'username': request.user.username if request.user.is_authenticated else 'Guest',
            'books': books
        }
        return render(request, 'home.html', context)
    recommended_books = recommend_books(request.user)
    random.shuffle(recommended_books)
    context = {
        'recommended_books': recommended_books[:4],
        'username': request.user.username if request.user.is_authenticated else 'Guest',
        'books': books
    }
    return render(request, 'home.html', context)

def recommend_books(user):
    profile = user.profile
    read_books = profile.read_books.all()
    read_authors = []
    for book in read_books:
        read_authors.append(book.author)
    recommended_books = []
    for author in read_authors:
        author_books = Book.objects.filter(author=author)
        for book in author_books:
            if book not in read_books:
                recommended_books.append(book)

    return recommended_books

book_check/views/profile.py
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse


@login_required
def profile(request):
    """
        Displaying page with information about the user and his read books.
    """
    profile = request.user.profile
    books = profile.read_books.all()
    return TemplateResponse(request, "profile.html",{
        "profile": profile,
        "read_books": books
    })

templates/author_detail.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author {{ author.name }}</title>
</head>
<body>
    <div class="container-singleBook">
        <h1>{{ author.name }}</h1>
        <p><strong class="years-of-life">Biography:</strong><br> {{ author.biography }}</p>
        <p><strong class="years-of-life">Years of life:</strong> {{ author.date_of_birth }} - {{ author.date_of_death }}</p>
    </div>

    <div class="container mt-5">
        <h2>Books:</h2>
        <ul>
            {% for book in author.books.all %}
                <li><a href="{% url 'book-detail' book.pk %}" class="author-book-link">{{ book.title }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <a href="{% url 'author-list' %}" class="btn btn-secondary mt-3">Back to Authors</a>
</body>
</html>
{% endblock %}

templates/author_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">List of Authors</h1>
    <hr>
    <ul id="book-list"  class="booklist-group">
        {% for author in authors %}
            <li class="booklist-group-item">
                <a href="{% url 'author_detail' author.pk %}" class="book-link">{{ author.name }} </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Book Lovers{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/logo3128x128.png' %}" type="image/x-icon" sizes="128x128">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
    <main>
        <header>
            <nav class="navbar navbar-expand-lg bg-body-tertiary bg-success-subtle text-success-emphasis fixed-top">
                <div class="container-fluid" >
                    <a  class="logo" href="{% url 'home' %}"><img src="{% static 'img/logo3128x128.png' %}" alt="Book Lovers Logo" width="50"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav justify-content-center">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'book-list' %}">Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'author-list' %}">Authors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                            </li>
                        </ul>
                        <form class="d-flex ms-auto" action="{% url 'book-search' %}" method="get">
                            <input class="form-control me-2" type="search" name="q" placeholder="Search books" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        {% if user.is_authenticated %}
                            <a class="btn btn-outline-success green-text" type="submit" href="{% url 'logout' %}" role="button">Logout</a>
                        {% else %}
                            <a class="btn btn-outline-success green-text" type="submit" href="{% url 'login' %}" role="button">Login</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>
        <div class="main-container">
            {% block content %}{% endblock %}
        </div>
    </main>

    <br>
<footer>
        <div class="footer">
            <div class="p-3 mb-2 ">
                <p>&copy; 2024 Book Lovers. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>

</html>

templates/book_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

{% block content %}
    <h1 class="text-center">Library</h1>
    <hr>
    <ul id="book-list" class="booklist-group">
        {% for book_obj in page_obj %}
            <li class="booklist-group-item">
                <h5><a href="{% url 'book-detail' book_obj.pk %}" class="book-link">{{ book_obj.title }}</a></h5>
                <p><strong>Author:</strong> {{ book_obj.author }}</p>
            </li>
        {% empty %}
            <li class="list-group-item">No books available in the library.</li>
        {% endfor %}
    </ul>
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation" class="my-5">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                  Previous
                </a>
              </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                  </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                  Next
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                  Last
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
    {% endif %}

    <a href="{% url 'home' %}" class="btn btn-secondary mt-3">Back to Home</a>
{% endblock %}

templates/book_search_results.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Search Results</h1>
    {% if books %}
        <ul class="booklist-group">
            {% for book in books %}
                <li class="booklist-group-item">
                    <a href="{% url 'book-detail' book.pk %}" class="book-link">
                        {{ book.title }} by {{ book.author.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books found matching your query.</p>
    {% endif %}
</div>
{% endblock %}

templates/footer.html
<div class="footer">
    <div class="p-3 mb-2 bg-success text-white fixed-bot">
        <p>&copy; 2024 Book Lovers. All rights reserved.</p>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}BookLovers{% endblock %}


{% block content %}

    <h1> Book Lovers - Welcome, {{ username }}!</h1>
    <h3 id="home-text"> This is&nbsp;a&nbsp;place where you can read, take notes and mark the history of&nbsp;what you read. </h3>
    <p id="home-text2"><strong>You can also set your own rating for books and tags for books.</strong></p></h1>



        <div class="container mt-5">
        <h1>Our Library</h1>
        <div class="card-group">
            {% for book in books %}
            <div class="card mx-2" style="width: 18rem;">
                <img src="{% if book.cover_image %}{{ book.cover_image.url }}{% else %}{% static 'img/default_cover.jpg' %}
                    {% endif %}" class="card-img-top" alt="Cover image">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">by {{ book.author.name }}</p>
                    <a href="{% url 'book-detail' book.pk %}" class="btn btn-success mt-auto">Go to Book</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


    <div class="container mt-5" >
        <h1>Recommendation for you</h1>
        <div class="card-group" style="width: 40rem;" id="recommendation-home">
            {% if recommended_books %}
                {% for book in recommended_books %}
                <div class="card mx-2" style="width: 18rem;">
                    <img src="{% if book.cover_image %}{{ book.cover_image.url }}{% else %}{% static 'img/default_cover.jpg' %}{% endif %}" class="card-img-top" alt="Cover image">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p class="card-text">by {{ book.author.name }}</p>
                        <a href="{% url 'book-detail' book.pk %}" class="btn btn-success mt-auto">Go to Book</a>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No recommendations available at this time.</p>
            {% endif %}
        </div>
    </div>



{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="signup_body w-50 p-4 border rounded shadow-sm bg-light">
        {% for error in form.non_field_errors %}{{ error }}
        {% endfor %}
        <h3> Please login</h3>
        <form class="login_form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3" >
                <label for="{{ form.username.id_for_label }}" class="form-label">
                    Username
                </label>
                {{ form.username|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="{{ form.password.id_for_label }}" class="form-label">
                    Password
                </label>
                {{ form.password|add_class:"form-control" }}
            </div>
            <div class="d-grid">
                <button class="btn btn-outline-success green-text"  type="submit">Log in</button>
            </div>
            <div class="text-center mt-3">
                <a href="/reset_password" class="d-block mb-2">Reset password</a>
                <p>Don't have an account?</p>
                <a class="btn btn-outline-success green-text" type="submit" href="/signup">Sign Up for Book Lovers</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Logout</h1>
    <hr>
    <div class="alert alert-success text-center p-5" style="background-color: #7FC597; color: white;">
        <p>You have been logged out successfully.</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Login again</a>
        <a href="{% url 'home' %}" class="btn btn-secondary">Go to Home Page</a>
    </div>
</div>
{% endblock %}

templates/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile - {{ profile.user.username }}{% endblock %}

{% block content %}
    <h1 class="text-center">Hello, {{ profile.user.username }}!</h1>
    <hr>
    <div class="containerProfile">
        <h3>Books you've read</h3>
        {% if read_books %}
            <ul class="booklist-group">
                {% for book in read_books %}
                    <li class="booklist-group-item">
                        <a href="{% url 'book-detail' book.pk %}" class="book-link">{{ book.title }}</a>
                        <span class="book-author">by {{ book.author.name }}</span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-muted">You haven't added any books yet.</p>
        {% endif %}
    </div>
    <hr>
    <form class="d-flex" action="{% url 'book-search' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search books by title or author" aria-label="Search" value="{{ request.GET.q }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <hr>



{#<div>#}
{##}
{#    <form id="add-book-form" method="POST">#}
{#        <h5>Add a Book</h5>#}
{#        {% csrf_token %}#}
{#        <div class="mb-3">#}
{#            <input type="text" id="book-title" name="book_title" class="form-control" placeholder="Enter full book Title" required>#}
{#        </div>#}
{#        <button type="submit" class="btn btn-outline-success">Add Book</button>#}
{#    </form>#}
{##}
{#    <ul id="book-list" class="mt-3">#}
{#    </ul>#}
{##}
{#    <p id="message" class="mt-3 text-danger"></p>#}
{#</div>#}
    <a href="{% url 'home' %}" class="btn btn-secondary">Back to Home</a>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="signup_body w-50 p-4 border rounded shadow-sm bg-light">
        <form class="login_form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Display form errors here -->
            {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                            {% endif %}
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <li>{{ form.non_field_errors|striptags }}</li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}

            <span class='label signup-title center-align d-block mb-4'>Sign up for free to read with Book Lovers.</span>

            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">
                    What's your name?
                    {% if form.username.errors %}
                        <span style="color:#f79862;">Username already exists</span>
                    {% endif %}
                </label>
                {{ form.username|add_class:"form-control" }}
            </div>

            <div class="mb-3">
                <label for="{{ form.email.id_for_label }}" class="form-label">
                    What's your email?
                    {% if form.email.errors %}
                        <span style="color:#f79862;">Email already exists</span>
                    {% endif %}
                </label>
                {{ form.email|add_class:"form-control" }}
            </div>

            <div class="mb-3">
                <label for="{{ form.password1.id_for_label }}" class="form-label">
                    Create a password
                </label>
                {{ form.password1|add_class:"form-control" }}
            </div>

            <div class="mb-3">
                <label for="{{ form.password2.id_for_label }}" class="form-label">
                    Confirm your password
                </label>
                {{ form.password2|add_class:"form-control" }}
            </div>

            <div class="d-grid mb-3">
                <button class="btn btn-primary btn_log_in" type="submit">Sign up</button>
            </div>

            <div class="text-center mt-3">
                <p>Already have an account? <a href="/login">Log in</a>.</p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/single_book.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-singleBook">
        <h1>{{ book.title }}</h1>
        <h4 class="text-muted">
            by <a href="{% url 'author_detail' book.author.pk %}"  class="book-link">{{ book.author.name }}</a>
        </h4>
        <p><strong>Published Date:</strong> {{ book.published_date }}</p>
        <p><strong>Genre:</strong> {{ book.get_genres_display }}</p>
        <p><strong>Description:</strong></p>
        <p>{{ book.description }}</p>
    </div>

    {% if is_authenticated %}
        {% if allow_add %}
            <div class="d-flex justify-content-start">
                <form action="{% url 'book-detail' book.pk %}" method="POST" class="me-2">
                    {% csrf_token %}
                    <input type="hidden" name="book_id" value="{{ book.pk }}">
                    <button type="submit" class="btn btn-primary">Add to My Books</button>
                </form>
            </div>
        {% endif %}
        <div class="mt-4">
            <h3>Your Notes and Review</h3>
            {% if user_interaction %}
                <p><strong>Rating:</strong> {{ user_interaction.rating }}</p>
                <p><strong>Tags:</strong> {{ user_interaction.tags }}</p>
                <p><strong>Notes:</strong> {{ user_interaction.note }}</p>
            {% else %}
                <p>No notes and review yet. Submit your review using the form above.</p>
            {% endif %}</div>
        <div>
            <h3>Make a record</h3>
            <form action="{% url 'book-detail' book.pk %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="book_id_review" value="{{ book.pk }}">

                <div class="form-rating">
                    <label for="{{ form.rating.id_for_label }}" class="form-label">Rating:</label>
                    {{ form.rating }}
                </div>

                <div class="form-tags">
                    <label for="{{ form.tags.id_for_label }}" class="form-label">Tags:</label>
                    {{ form.tags }}
                </div>

                <div class="form-note">
                    <label for="{{ form.note.id_for_label }}" class="form-label">Note:</label>
                    {{ form.note }}
                </div>

                <button type="submit" class="btn btn-primary">Add to My Notes</button>
            </form>
        </div>
    {% else %}
         <p id="singlebook-text2"><strong>Sorry, you can`t use other features without authorization</strong></p></h1>
    {% endif %}
    <a href="{% url 'book-list' %}" class="btn btn-secondary mt-3">Back to Library</a>
{% endblock %}